using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using Unity.Mathematics;
using UnityEngine;

public class Solitaire : MonoBehaviour
{
    public AudioSource audioSource;
    public AudioClip pickSound;
    public GameObject victoryScreen;
    public GameObject cardPrefab;
    public Sprite emptyPlace;
    public String[] suits = { "C", "D", "H", "S" };
    public String[] ranks = {"A", "2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K"};
    public Sprite[] cardFaces;
    public Sprite cardBack;
    public GameObject[] foundationPositions;
    public GameObject[] tableauPositions;
    public GameObject deckPosition;
    public GameObject wastePosition;
    public List<string> deck;
    public List<string> waste;
    public List<string>[] foundations;
    public List<string>[] tableaus;
    public List<string> foundation0 = new List<string>();
    public List<string> foundation1 = new List<string>();
    public List<string> foundation2 = new List<string>();
    public List<string> foundation3 = new List<string>();
    public List<string> tableau0 = new List<string>();
    public List<string> tableau1 = new List<string>();
    public List<string> tableau2 = new List<string>();
    public List<string> tableau3 = new List<string>();
    public List<string> tableau4 = new List<string>();
    public List<string> tableau5 = new List<string>();
    public List<string> tableau6 = new List<string>();
    public List<string> tableau7 = new List<string>();
    public GameObject[] freeCellPositions;
    public List<string>[] freeCells;
    public List<string> freeCell0 = new List<string>();
    public List<string> freeCell1 = new List<string>();
    public List<string> freeCell2 = new List<string>();
    public List<string> freeCell3 = new List<string>();
    private System.Random rng = new System.Random();
    private Vector3 cardOffset = new Vector3(0f, -.3f, -0.1f);
    private float zOffset = -.3f;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        tableaus = new List<string>[] { tableau0, tableau1, tableau2, tableau3, tableau4, tableau5, tableau6, tableau7 };
        foundations = new List<string>[] { foundation0, foundation1, foundation2, foundation3 };
        freeCells = new List<string>[] { freeCell0, freeCell1, freeCell2, freeCell3 };
        PlayGame();
    }

    // Update is called once per frame
    void Update()
    {

    }

    void PlayGame()
    {
        deck = GenerateDeck();
        foreach (string card in deck)
        {
            Debug.Log(card);
        }
        Deal();
    }

    public bool CheckVictory()
    {
        GameObject[] foundations = GameObject.FindGameObjectsWithTag("Foundation");

        foreach (GameObject foundation in foundations)
        {
            if (foundation.transform.childCount < 13)
                return false;
        }

        return true;
    }


    List<string> GenerateDeck()
    {
        List<string> newDeck = new List<string>();
        foreach (string suit in suits)
        {
            foreach (string rank in ranks)
            {
                newDeck.Add(suit + rank);
            }
        }
        //shuffle
        newDeck = newDeck.OrderBy(x => rng.Next()).ToList();
        return newDeck;
    }

    void Deal()
        {
        int tabIndex = 0;
        int cardIndex = 0;
        for (int i = deck.Count - 1; i >= 0; i--)
        {
            string card = deck[i];
            if(tabIndex <= 3)
            {
                deck.RemoveAt(i);
                tableaus[tabIndex].Add(card);
                cardIndex++;
                if(cardIndex == 7)
                {
                    cardIndex = 0;
                    tabIndex++;
                }
            } else if(tabIndex <= 7)
            {
                deck.RemoveAt(i);
                tableaus[tabIndex].Add(card);
                cardIndex++;
                if(cardIndex == 6)
                {
                    cardIndex = 0;
                    tabIndex++;
                }
            }
            else
            {
                Debug.Log("No more tableaus");
                Debug.Log("Current tabelau: " + tabIndex);
                Debug.Log("Current card index: " + cardIndex );
                Debug.Log("Cards left in deck: " + i);
            }
                
        }

        foreach (GameObject tabPosition in tableauPositions)
        {
            Debug.Log("Dealing to tableau position " + tabPosition.name);
            int index = Array.IndexOf(tableauPositions, tabPosition);
            Vector3 currentPosition = tabPosition.transform.position + new Vector3(0, 0, -.1f);
            foreach (string card in tableaus[index])
            {
                Debug.Log("Dealing card " + card + " to tableau " + index);
                // create card
                CreateCard(card, currentPosition, tabPosition.transform, true);
                currentPosition += cardOffset;
            }
        }
    }

    void CreateCard(string cardName, Vector3 position, Transform parent, bool isFaceUp)
    {
        Debug.Log("Creating card " + cardName + " at " + position);
        GameObject newCard = Instantiate(cardPrefab, position, Quaternion.identity, parent);
        newCard.name = cardName;
        Sprite cardFace = cardFaces.FirstOrDefault(s => s.name == cardName);
        newCard.GetComponent<CardSprite>().cardFace = cardFace;
        newCard.GetComponent<CardSprite>().isFaceUp = isFaceUp;
    }

    public void DrawFromDeck()
    {
        Debug.Log("Drawing from deck");
        if (deck.Count == 0)
        {
            while (waste.Count > 0)
            {
                string card = waste.Last();
                waste.RemoveAt(waste.Count - 1);
                deck.Add(card);
            }
            foreach (Transform child in wastePosition.transform)
            {
                Destroy(child.gameObject);
            }
            zOffset = -.3f;
            deckPosition.transform.GetComponent<SpriteRenderer>().sprite = cardBack;
            return;
        }

        // need to reset x position for all cards not in the drawn set of 3
        foreach (Transform child in wastePosition.transform)
        {
            child.transform.position = new Vector3(wastePosition.transform.position.x, child.transform.position.y, child.transform.position.z);
        }
        int cardsToDraw = Math.Min(3, deck.Count);
        for (int i = 0; i < cardsToDraw; i++)
        {
            string card = deck.Last();
            deck.RemoveAt(deck.Count - 1);
            waste.Add(card);
            CreateCard(card, wastePosition.transform.position + new Vector3(i * 0.3f, 0, zOffset), wastePosition.transform, true);
            zOffset -= .3f;
        }
        
        Debug.Log("Deck count: " + deck.Count);
        if (deck.Count == 0)
        {
            // show empty deck
            deckPosition.transform.GetComponent<SpriteRenderer>().sprite = emptyPlace;
        }
    }

public bool IsValidMove(GameObject cardObject, GameObject targetObject)
{
    if (cardObject == null || targetObject == null || cardObject == targetObject)
    {
        StartCoroutine(ShakeCard(cardObject));
        return false;
    }

    ResolveTarget(targetObject, out GameObject clickedTag, out int foundationIndex, out int tabIndex, out int freeIndex);

    bool canMove = false;

    string parentTag = cardObject.transform.parent.tag;
    string targetTag = clickedTag.transform.tag;

    if (targetTag == "FreeCell" && freeIndex >= 0)
    {
        bool freeEmpty = freeCells[freeIndex].Count == 0;

        if (!freeEmpty)
        {
            canMove = false;
            StartCoroutine(ShakeCard(cardObject));
            return false;
        }

        if (parentTag == "Tableau")
        {
            if (IsLastInTab(cardObject))
                canMove = true;
            else
                canMove = false;
        }
        else
        {
            canMove = true;
        }

        if (!canMove)
            StartCoroutine(ShakeCard(cardObject));
        return canMove;
    }

    if (parentTag == "Waste")
    {
        if (targetTag == "Tableau" && tabIndex >= 0)
            canMove = CanPlaceOnTableau(cardObject.name, tabIndex);
        else if (targetTag == "Foundation" && foundationIndex >= 0)
            canMove = CanPlaceOnFoundation(cardObject.name, foundationIndex);
    }
    else if (parentTag == "Foundation")
    {
        if (targetTag == "Tableau" && tabIndex >= 0)
            canMove = CanPlaceOnTableau(cardObject.name, tabIndex);
    }
    else if (parentTag == "Tableau")
    {
        if (targetTag == "Tableau" && tabIndex >= 0)
            canMove = CanPlaceOnTableau(cardObject.name, tabIndex);
        else if (targetTag == "Foundation" && foundationIndex >= 0 && !IsBlocked(cardObject))
            canMove = CanPlaceOnFoundation(cardObject.name, foundationIndex);
    }
    else if (parentTag == "FreeCell")
    {
        if (targetTag == "Tableau" && tabIndex >= 0)
            canMove = CanPlaceOnTableau(cardObject.name, tabIndex);
        else if (targetTag == "Foundation" && foundationIndex >= 0)
            canMove = CanPlaceOnFoundation(cardObject.name, foundationIndex);
    }

    if (!canMove)
        StartCoroutine(ShakeCard(cardObject));

    return canMove;
}


// Coroutine to shake the card
private IEnumerator ShakeCard(GameObject card)
{
    if (card == null) yield break;

    Vector3 originalPos = card.transform.localPosition;
    float elapsed = 0f;
    float duration = 0.3f;
    float magnitude = 0.2f;

    while (elapsed < duration)
    {
        float x = UnityEngine.Random.Range(-1f, 1f) * magnitude;
        float y = UnityEngine.Random.Range(-1f, 1f) * magnitude;

        card.transform.localPosition = originalPos + new Vector3(x, y, 0);
        elapsed += Time.deltaTime;
        yield return null;
    }

    card.transform.localPosition = originalPos;
}

    public void MoveCardsAbove(GameObject origParent, int originalTabIndex, int destTabIndex, int cardsToMoveCount, GameObject clickedTag, GameObject cardObject)
    {
        if (originalTabIndex == -1 || cardsToMoveCount <= 1) return;
        List<string> origTab = tableaus[originalTabIndex];
        int origCount = origTab.Count;
        int origIndex = origCount - cardsToMoveCount + 1;
        for (int i = 0; i < cardsToMoveCount -1 ; i++)
        {
            string movingCardName = origTab[origIndex];
            origTab.RemoveAt(origIndex);
            tableaus[destTabIndex].Add(movingCardName);
            GameObject movingCardObj = null;
            foreach (Transform child in origParent.transform)
            {
                if (child.gameObject.name == movingCardName)
                {
                    movingCardObj = child.gameObject;
                    break;
                }
            }
            if(movingCardObj!=null)
            {
                movingCardObj.transform.parent = clickedTag.transform;
                movingCardObj.transform.position = cardObject.transform.position + (cardOffset * (i + 1));
            }
        }
    }
    
    public void PlaceCard(GameObject cardObject, GameObject targetObject)
    {
        if (cardObject == targetObject || cardObject == null || targetObject == null) return;
        int originalTabIndex = -1;
        int cardsToMoveCount = 1;
        ResolveTarget(targetObject, out GameObject clickedTag, out int foundationIndex, out int tabIndex, out int freeIndex);
        GameObject originalParent = cardObject.transform.parent.gameObject;
        // if coming from tab, need to remove card and all cards on top of it from their original tab
        if (originalParent.CompareTag("FreeCell"))
        {
            foreach (List<string> free in freeCells)
            {
                if (free.Contains(cardObject.name))
                {
                    free.Remove(cardObject.name);
                    break;
                }
            }
        }
        if (cardObject.transform.parent.CompareTag("Tableau"))
        {
            foreach (List<string> tableau in tableaus)
            {
                if (tableau.Contains(cardObject.name))
                {
                    originalTabIndex = System.Array.IndexOf(tableaus, tableau);
                    cardsToMoveCount = tableau.Count - tableau.IndexOf(cardObject.name);
                    tableau.Remove(cardObject.name);
                    break;
                }
            }
        }

        if (cardObject.transform.parent.CompareTag("Waste"))
        {
            waste.Remove(cardObject.name);
        }
        // if coming from foundation, remove card from correct foundation
        if (cardObject.transform.parent.CompareTag("Foundation"))
        {
            foreach (List<string> foundation in foundations)
            {
                if (foundation.Contains(cardObject.name))
                {
                    foundation.Remove(cardObject.name);
                }
            }
        }

        // if moving to tab, add the card to the correct tab
        if (clickedTag.transform.CompareTag("Tableau"))
        {
            // add it to the right tab
            int tableauIndex = System.Array.IndexOf(tableauPositions, clickedTag);
            tableaus[tableauIndex].Add(cardObject.name);
            // move the card position
            if (tableaus[tableauIndex].Count == 1)
                cardObject.transform.position = targetObject.transform.position + new Vector3(0f, 0f, -.03f);
            else
                cardObject.transform.position = targetObject.transform.position + cardOffset;
            // update parent
            cardObject.transform.parent = clickedTag.transform;
            // move all other cards on top of the original cardObject (probably put this in a helper function)
            MoveCardsAbove(originalParent, originalTabIndex, tableauIndex, cardsToMoveCount, clickedTag, cardObject);
        }
        // if moving to foundation, add card to correct foundation
        if (clickedTag.transform.CompareTag("Foundation"))
        {
            int fIndex = System.Array.IndexOf(foundationPositions, clickedTag);
            foundations[fIndex].Add(cardObject.name);
            cardObject.transform.position = targetObject.transform.position + new Vector3(0f, 0f, -.03f);
            cardObject.transform.parent = clickedTag.transform;
        }
        if (clickedTag.CompareTag("FreeCell"))
        {
            int fIndex = Array.IndexOf(freeCellPositions, clickedTag);

            freeCells[fIndex].Add(cardObject.name);

            cardObject.transform.position = clickedTag.transform.position + new Vector3(0, 0, -.03f);
            cardObject.transform.parent = clickedTag.transform;

            return;
        }

        if (CheckVictory())
        {
            Debug.Log("Victory!");
            victoryScreen.SetActive(true);
        }
        audioSource.PlayOneShot(pickSound);
    }
    public bool IsLastInTab(GameObject cardObject)
    {
        foreach(List<string> tab in tableaus)
        {
            if (tab.Count > 0 && tab.Last() == cardObject.name)
            {
                return true;
            }
        }
        return false;
    }

    public bool IsBlocked(GameObject cardObject)
    {
        foreach (Transform child in cardObject.transform.parent)
        {
            if (child.gameObject != cardObject && child.position.z < cardObject.transform.position.z)
            {
                return true;
            }
        }
        return false;
    }

    public bool IsAlternatingColor(string card1, string card2)
    {
        if (card1 == null || card2 == null) return false;
        char suit1 = card1[0];
        char suit2 = card2[0];
        bool isRed1 = (suit1 == 'D' || suit1 == 'H');
        bool isRed2 = (suit2 == 'D' || suit2 == 'H');
        return isRed1 != isRed2;
    }

    public bool IsSameSuit(string card1, string card2)
    {
        if (card1 == null || card2 == null) return false;
        return card1[0] == card2[0];
    }

    public bool IsOneRankHigher(string card1, string card2)
    {
        if (card1 == null || card2 == null) return false;
        int rank1 = Array.IndexOf(ranks, card1.Substring(1));
        int rank2 = Array.IndexOf(ranks, card2.Substring(1));
        Debug.Log("rank1: " + rank1);
        Debug.Log("rank2: " + rank2);
        return rank1 == (rank2 + 1) % ranks.Length;
    }

    public bool IsOneRankLower(string card1, string card2)
    {
        if (card1 == null || card2 == null) return false;
        int rank1 = Array.IndexOf(ranks, card1.Substring(1));
        int rank2 = Array.IndexOf(ranks, card2.Substring(1));
        return (rank1 + 1) % ranks.Length == rank2;
    }

    public bool CanPlaceOnFoundation(string card, int foundationIndex)
    {
        if (foundations[foundationIndex].Count == 0)
        {
            return card.Substring(1) == "A";
        }
        string topCard = foundations[foundationIndex].Last();
        Debug.Log("topCard: " + topCard + ", card: " + card);
        Debug.Log("IsSameSuit: " + IsSameSuit(card, topCard));
        Debug.Log("IsOneRankHigher: " + IsOneRankHigher(card, topCard));
        return IsSameSuit(card, topCard) && IsOneRankHigher(card, topCard);
    }

    public bool CanPlaceOnTableau(string card, int tableauIndex)
    {
        if (tableaus[tableauIndex].Count == 0)
        {
            return true;
        }
        string topCard = tableaus[tableauIndex].Last();
        return IsAlternatingColor(card, topCard) && IsOneRankLower(card, topCard);
    }

    void ResolveTarget(GameObject toLocation, out GameObject clickedTag, out int foundationIndex, out int tableauIndex, out int freeCellIndex)
    {
        clickedTag = toLocation.transform.CompareTag("Card")
            ? toLocation.transform.parent.gameObject
            : toLocation;

        foundationIndex = -1;
        tableauIndex = -1;
        freeCellIndex = -1;

        if (clickedTag.CompareTag("Foundation"))
            foundationIndex = Array.IndexOf(foundationPositions, clickedTag);
        else if (clickedTag.CompareTag("Tableau"))
            tableauIndex = Array.IndexOf(tableauPositions, clickedTag);
        else if (clickedTag.CompareTag("FreeCell"))
            freeCellIndex = Array.IndexOf(freeCellPositions, clickedTag);
    }
}
